services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: danuanastasia/front:latest
    restart: always
    ports:
      - 3000:80
    environment:
      - VITE_API_URL=https://localhost:8443
      - VITE_VERSION=2
      - VITE_CREDENTIALS=true
