/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type IngredientDTO = {
  /**
   * @format int64
   */
  id?: number;
  ingredient?: string;
  /**
   * @format int64
   */
  amount?: number;
  measure?: string;
};

export type RecipeDTO = {
  /**
   * @format int64
   */
  id?: number;
  keycloakId?: string;
  image?: string;
  title?: string;
  description?: string;
  contents?: string;
  tags?: Tag[];
  ingredients?: IngredientDTO[];
};

export type Tag = {
  /**
   * @format int64
   */
  id?: number;
  tag?: string;
};

export type ShortRecipeDTO = {
  /**
   * @format int64
   */
  id?: number;
  keycloakId?: string;
  image?: string;
  title?: string;
};
