/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type IngredientDTO = {
  /**
   * @format int64
   */
  id?: number;
  ingredient?: string;
  /**
   * @format int64
   */
  amount?: number;
  measure?: string;
};

export type RecipeDTO = {
  /**
   * @format int64
   */
  id?: number;
  keycloakId?: string;
  image?: string;
  title?: string;
  description?: string;
  contents?: string;
  tags?: Tag[];
  ingredients?: IngredientDTO[];
};

export type Tag = {
  /**
   * @format int64
   */
  id?: number;
  tag?: string;
};

export type ShortRecipeDTO = {
  /**
   * @format int64
   */
  id?: number;
  keycloakId?: string;
  image?: string;
  title?: string;
};

export type PageImpl = {
  content?: Record<string, any>[];
  pageable?: PageableObject;
  /**
   * @format int32
   */
  totalPages?: number;
  /**
   * @format int64
   */
  totalElements?: number;
  last?: boolean;
  /**
   * @format int32
   */
  size?: number;
  /**
   * @format int32
   */
  number?: number;
  sort?: SortObject;
  first?: boolean;
  /**
   * @format int32
   */
  numberOfElements?: number;
  empty?: boolean;
};

export type PageableObject = {
  /**
   * @format int64
   */
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  /**
   * @format int32
   */
  pageSize?: number;
  /**
   * @format int32
   */
  pageNumber?: number;
  unpaged?: boolean;
};

export type SortObject = {
  empty?: boolean;
  unsorted?: boolean;
  sorted?: boolean;
};
