/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/consistent-indexed-object-style */
/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type UserListRepresentationDTO = {
  id?: string;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  emailVerified?: boolean;
  attributes?: {
    [key: string]: string[];
  };
  userProfileMetadata?: UserProfileMetadata;
};

export type UserProfileAttributeGroupMetadata = {
  name?: string;
  displayHeader?: string;
  displayDescription?: string;
  annotations?: {
    [key: string]: Record<string, any>;
  };
};

export type UserProfileAttributeMetadata = {
  name?: string;
  displayName?: string;
  required?: boolean;
  readOnly?: boolean;
  annotations?: {
    [key: string]: Record<string, any>;
  };
  validators?: {
    [key: string]: {
      [key: string]: Record<string, any>;
    };
  };
  group?: string;
  multivalued?: boolean;
};

export type UserProfileMetadata = {
  attributes?: UserProfileAttributeMetadata[];
  groups?: UserProfileAttributeGroupMetadata[];
};

export type UserPublicRepresentationDTO = {
  id?: string;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  emailVerified?: boolean;
  attributes?: {
    [key: string]: string[];
  };
  userProfileMetadata?: UserProfileMetadata;
  picture?: string;
  bio?: string;
};
